export interface User {
  id: string,
  login: string,
  display_name: string,
  type: string,
  broadcaster_type: string,
  description: string,
  profile_image_url: string,
  offline_image_url: string,
  view_count: number,
  email: string,
  /* displayName: string,
  email: string,
  photoURL?: string,
  twitchDisplayName?: string,
  twitchEmail?: string,
  twitchId?: string,
  twitchLogin?: string,
  twitchURL?: string,
  uid: string */
}
